### ISSUE TITLE
configure: error: Detected LibreSSL: This is NOT supported, and may break consensus compatibility!

### ISSUE THREAD

**Issue by Timur-m4m** [merocoin/mero#2]
System - Debian-9-x86_64

I am trying to run master node and when I run ./configure command it return:

> configure: error: Detected LibreSSL: This is NOT supported, and may break consensus compatibility!

How can it be resolved?

**Comment by Timur-m4m** [comment]
> apt-get install libssl1.0-dev
Resolved this problem

**Comment by Timur-m4m** [comment]
> apt-get install libssl1.0-dev

Resolved this problem

**Comment by ghost** [comment]
Got `Package 'libssl1.0-dev' has no installation candidate` while running sudo apt-get install libssl1.0 -dev
